[package]
name = "app"
version = "0.1.0"
authors = ["Thomas <thomasr1987@gmail.com>"]
edition = "2021"

[dependencies]
bevy = { workspace = true }
emulator = { path = "../emulator" }
files = { path = "../files" }
